config/routes.rb
Getgroups::Application.routes.draw do
  get '/groups/index' => 'groups#index'

  resources :groups do
    
    resources :people
    resources :announcements
  end
  
   devise_for :users, :controllers => { :registrations => "users/registrations" }

  get 'api/announcements'
  get 'api/groups'
  get 'api/group'
  post 'api/check_token'

  root 'home#index'

  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
	attr_accessible :content, :group_id
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	
	# Basic 
	attr_accessible :title, :info

  	attr_accessible :logo
  	has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "64x64>" }, :default_url => "/assets/missing64.png"

	# Admin
	belongs_to :user

	# Contacts
	has_many :people
	has_many :announcements

	# Validations
	validates :title, :presence => true
	validates :info, :presence => true
end

app/models/person.rb
class Person < ActiveRecord::Base
	# Basic Identity
	attr_accessible :first_name, :last_name, :token

	# Contacts
	attr_accessible :phone, :phone_scnd, :fax, :email, :url

	# Business
	attr_accessible :job_title, :department

	attr_accessible :avatar
  	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "32x32" }, :default_url => "/assets/missing64.png"

	# Relations
	belongs_to :group

	before_create :generate_token

	# Validations
	validates :first_name, :presence => true
	validates :last_name, :presence => true
	validates :email, :presence => true
	validates :phone, :presence => true
	validates :job_title, :presence => true
	# validates :avatar, :presence => true

	def generate_token
		o =  [('a'..'z'),('A'..'Z')].map{|i| i.to_a}.flatten
        self.token = (0...10).map{ o[rand(o.length)] }.join
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  attr_accessible :email, :password, :first_name, :password_confirmation, :last_name
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	def create
	  @group = Group.find(params[:group_id])
	  @announcement  = @group.announcements.new(params[:announcement])
	    respond_to do |format|
	      if @announcement.save
	        # format.js 
	        format.html { redirect_to @group }
	      else
	        format.html { render action: "index" }
	      end
	    end    
	end

	def show
		
	end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	def announcements
		begin
			tokens = params[:tokens].split(',')
			people = Person.where(token: tokens)
			groups = []
			anns = []

			people.each { |p| groups << p.group.id }

			Announcement.where(group_id: groups).each {|a| anns << {group_name: a.group.title, content: a.content} }

			render json: anns
		rescue Exception => e  
			render :json => { error: e }
		end
	end

	def groups


		begin
			tokens = params[:tokens].split(',')
			people = Person.where(token: tokens)
			groups = []

			people.each { |p| groups << {id: p.group.id, title: p.group.title } }

			render json: groups
		rescue Exception => e  
			render :json => { error: e }
		end
	end

	def group
		group_id = params[:id]

		begin
			# people = Person.where(token: tokens)
			people = []

			Group.find(group_id).people.each do |p| 
				people << {
					id: p.id, 
					first_name: p.first_name, 
					last_name: p.last_name,
					phone: p.phone,
					photo: URI.join(request.url, p.avatar.url(:thumb)).to_s 
				}
			end

			logger.debug people.inspect

			render json: people
		rescue Exception => e  
			render :json => { error: e }
		end

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_filter :update_sanitized_params, if: :devise_controller?

	def update_sanitized_params
	  devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :password, :password_confirmation, :email)}
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @user = current_user
    @groups = @user.groups
    @group = Group.new
    @group.user_id = current_user.id
    
  end

  def create
  @group = Group.new(params[:group])
  @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        # format.js 
        format.html { redirect_to @group }
      else
        format.html { render action: "index" }
      end
    end     
  end

  def update
  end

  def delete
  end

  def show
    @group = Group.find(params[:id])
    @person = @group.people.build
    @announcement = @group.announcements.build
  end

  def new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end

	def settings
		@user = current_user
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def create
	  @group = Group.find(params[:group_id])
	  @person  = @group.people.new(params[:person])
    respond_to do |format|
      if @person.save
        # format.js 
        format.html { redirect_to @group }
      else
        format.html { render action: "index" }
      end
    end     
  end

  def destroy
  @group = Group.find(params[:group_id])
  @person = @group.people.find(params[:id])
  @person.destroy
  respond_to do |format| 
    format.html { redirect_to @group }
    # format.js 
  end
end


end

app/controllers/users/registrations_controller.rb
 class Users::RegistrationsController < Devise::RegistrationsController
 	
 end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/announcements/_new_pop.html.erb
<div class="basic-pop-up">
	<%= image_tag 'broadcast_icon.png', class: 'page-icon' %>
	<h1>A new announcement</h1>
	<%= form_for([@group, @announcement],  :html => { class: 'pure-form center-it'}) do |f| %>
		<%= f.text_area :content, :class => 'annc' %> <br /><br />
		<div><%= f.submit 'Push', :class => 'pure-button pure-button-secondary center-it' %></div>
	<% end %>
</div>

app/views/groups/_new_pop.html.erb
<div class="basic-pop-up">
	<%= image_tag 'new_group_ma_akesher.png', class: 'page-icon' %>
	<h1>A new group</h1>
	<%= form_for(@group,  :html => { class: 'pure-form center-it'}) do |f| %>
			  <%= f.text_field :title, :placeholder => 'Group name', :class => 'center-it'  %><br/><br/>
			  <%= f.text_area :info, :placeholder => 'Some info', :class => 'textarea center-it' %><br/>
		    <%= f.file_field :logo %>

			<div><%= f.submit 'Create', :class => 'pure-button pure-button-secondary center-it' %></div>
	<% end %>

</div>

app/views/groups/_token_pop.html.erb
<div class="basic-pop-up">
	<%= image_tag 'new_token.png', class: 'page-icon' %>
	<h1>A new user token</h1>
	<h4 style="text-align:center;">AJSDFAsjk44lj42lasF</h4>


</div>

app/views/groups/delete.html.erb
<h1>Groups#delete</h1>
<p>Find me in app/views/groups/delete.html.erb</p>

app/views/groups/index.html.erb
<script type="text/javascript">
$(document).ready(function(){
  var new_group_modal = "<%= escape_javascript(render(:partial => 'groups/new_pop')) %>"

      $('#new-group').colorbox({
		html:new_group_modal,
		transition:"none",
		speed:800,
		fadeOut:200,
		width:590,
		height:460,
		fixed:true, 
		className:'issue-modal'
});
});
</script>
<div class="center-header">
	<%= image_tag 'settings01.png', class: 'center'  %><br />
	<h2>Dashboard</h2>
</div>
<div class="groups-title">
<h4 class="groups-h4"><%= current_user.first_name %>'s groups</h4> 
<button id="new-group" class="pure-button pure-button-secondary inline-right">New Group</button>
</div>
<br clear="all" />
<div class="company-listing">
	<ul>
		<% if current_user.groups.size == 0 %>
			<h1 style="font-size:18pt; font-weight:200;">No groups yet.</h1>
		<% end %>

		<% current_user.groups.each do |group| %>
		
		<li>
			<div class="company-listing-logo">
				<%= image_tag group.logo.url(:thumb) %>
			</div>
			<div class="company-info">
				<%= link_to group.title, group %>
				<p><%= group.info %></p>
			<div class="icons_list">
				<%= image_tag 'users_icon.png', class: 'gray-icon' %> &nbsp;  <%= group.people.size %>  
				<%= image_tag 'stats_icon.png', class: 'gray-icon' %> 123
			</div>
			</div>
		</li><br />
		<% end %>
	</ul>

</div>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<script type="text/javascript">
$(document).ready(function(){
  var new_person_modal = "<%= escape_javascript(render(:partial => 'people/new_pop')) %>"

      $('#new-person').colorbox({
		html:new_person_modal,
		transition:"none",
		speed:800,
		fadeOut:200,
		width:750,
		height:580,
		fixed:true, 
		className:'issue-modal'
});
        var new_announcement_modal = "<%= escape_javascript(render(:partial => 'announcements/new_pop')) %>"

      $('#new-announcement').colorbox({
        html:new_announcement_modal,
        transition:"none",
        speed:800,
        fadeOut:200,
        width:650,
        height:480,
        fixed:true, 
        className:'issue-modal'
});
    
    var new_announcement_modal = "<%= escape_javascript(render(:partial => 'token_pop')) %>"

      $('#new-token').colorbox({
        html:new_announcement_modal,
        transition:"none",
        speed:800,
        fadeOut:200,
        width:650,
        height:480,
        fixed:true, 
        className:'issue-modal'
});


});
</script>


<div class="l-content centered-text" >
<%= image_tag @group.logo.url(:medium), class: 'group-logo' %>
<h1 style="margin:0;"><%= @group.title %></h1>
<p style="margin:0;"><%= @group.info %></p>

<br /><br />
<div class="left-side-contacts"> 
    <h4 style="text-align:left; padding-left:14px; font-weight: 300; border-left: solid 1px #42b8dd;">Announcements</h4>
    <% if @group.announcements.size == 1 %>
    <h1 style="text-align:left; font-weight: 300;">No announcements yet.</h1>
    <% else %>
    <ul>
        <% @group.announcements.each do |anc| %>
        <% if anc.persisted? %>
       <li style="text-align:left; margin-top:14px; font-weight: 300; color:#888;">  
          <%= truncate(anc.content, length: 80) %>
        </li>
        <% end %>
        <% end %>

    </ul>

    <% end %>
    
</div>

<div class="left-side-contacts"> 
    <h4 style="text-align:left; padding-left:14px; font-weight: 300; border-left: solid 1px #42b8dd;">People</h4>
    <% if @group.people.size == 1 %>

    	<h1 style="text-align:left; font-weight: 300;">No people yet.</h1>
    <% else %>
	<table class="pure-table pretty">
    <thead>
        <tr>
            <th class="img-column"></th>
            <th>Full Name</th>
            <th>Title</th>
            <th>Phone #1</th>
            <th>Email</th>
            <th class="tiny-column">X</th>
        </tr>
    </thead>

    <tbody>
    	<% cnt = 1 %>

    	<% @group.people.each do |person| %>
    	<% if person.persisted? %>
    	<% if (cnt % 2)==0 %>
    	<tr class="pure-table-odd">
    	<% else %>
		<tr class="pure-table-even">
    	<% end %>
        
        	<td class="img-column"><%= image_tag person.avatar.url(:thumb), class: 'tiny-user' %></td>
            <td><%= person.first_name + ' ' + person.last_name %></td>
            <td><%= person.job_title  %></td>
            <td><%= person.phone  %></td>
            <td><%= person.email  %></td>
            <td><%= link_to 'X', group_person_path(@group, person), :confirm => "are you sure?", :remote => false, :method => :delete %></td>
        </tr>
        <% cnt+=1 %>
        <% end %>
        <% end %>
 	<% end %>
    </tbody>
</table>
</div>



<div class="right-side-contacts"> 
	<button id="new-announcement" class="pure-button pure-button-secondary pure-button-small">Broadcast</button><br /> <br />
	<button class="pure-button pure-button-secondary pure-button-small" id="new-person">New Person</button><br /> <br />
	<button id="new-token" class="pure-button pure-button-secondary pure-button-small">New Token</button> <br /> <br />
	<button class="pure-button pure-button-secondary pure-button-small">Share via Email</button><br /><br />
    <h5>Export to:</h5>
    <%= image_tag 'googlecontacts.png' %>
    <%= image_tag 'excelcontacts.png' %>
    <%= image_tag 'yahoocontacts.png' %>

</div>
</div>

app/views/home/index.html.erb
<%= content_for :banner do %>

		<div class="banner">
      <div class="wrapper-grid"><br/><br/><br/><br/>
        <br/><br/><br/><br/><br/>
        <br/><br/><br/><br/><br/>
      <h1 class="banner-head">
          Regrouping your contact list.<Br />
          Very useful.

      </h1><Br /><Br />
      <% if !user_signed_in? %>
<%= link_to 'Join Today', new_user_registration_path, class: 'pure-button pure-button-primary bigger float-left' %>
    <% else %>
    <%= link_to 'Form a new Group', groups_path, class: 'pure-button pure-button-primary bigger float-left' %>
<% end %>
    </div>
    </div>
<% end %>

<%= content_for :fullwidth do %>

<!-- <div class="fullwidth">
<div class="wrapper-grid"><br />
  <div style="float:left; display:inline-block; width:500px;">
  <h1>Regrouping your contacts</h1>
  <p style="color:#888; font-size:14pt; font-weight:300;" >
    Some marketing text is here.
      Some marketing text is here.<br /><br />
        Some marketing text is here.  Some marketing text is here.
  </p>
  </div>
  <div style="float:right; display:inline-block; width:300px;">
    asd
</div>

</div>
<br clear="all" /> -->
<div class="fullwidth">
  <br />
  <div class="wrapper-grid">
  <h1>Regrouping your contacts</h1>
  <p style="color:#888; font-size:14pt; font-weight:300;" >
    Some marketing material
  </p>
</div>
</div>
<% end %>

app/views/layouts/application.html.erb
        <% user_signed_in? ? logo_path = groups_path : logo_path = root_path %>

<!DOCTYPE html>
<html>
<head>
  <title>getGroups</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  

    <div class="pure-menu pure-menu-fixed pure-menu-open pure-menu-horizontal float-right">
      <div class="wrapper-grid">
          <a href="#" class="">
      <%= link_to image_tag('small_logo.PNG', class: 'displ-inline'), logo_path %>
    </a>
    <ul class="new-menu-because-pure-sucks">
      <li class="pure-menu-selected"><a href="/">Home</a></li>
      <% if user_signed_in? %>
        
        <li><%= link_to 'My Groups', groups_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        
      <% else %>
        <li><%= link_to 'Sign Up / Sign In', new_user_registration_path %>
          </li>
      <% end %>
    </ul>
</div>
</div>



<%= yield(:banner) %>
<%= yield(:fullwidth) %>
<div class="l-content">
<%= yield %>
</div>

<Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br /><Br />
<div class="footer">
  <div class="wrapper-grid">
    <p class="l-box">
      <%= image_tag 'small_logo_grayscale.png' %>
        <a href="#">getGroups</a> Built in less than 24hrs in Yahoo! Hack Israel.
    </p>
    </div>
</div>
</body>
</html>

app/views/people/_new_pop.html.erb
<div class="basic-pop-up">
	<%= image_tag 'user.png', class: 'page-icon' %>
	<h1>A new person</h1>
<Br /><Br />
	<div class="left-side-new-person">
 <% image_tag 'user_add_image.png', class: 'user_add_image' %>
	<%= form_for([@group, @person],  :html => { class: 'pure-form center-it'}) do |f| %>
			  <%= f.text_field :first_name, :placeholder => 'First name', :class => 'center-it'  %><br/><br/>
			  <%= f.text_field :last_name, :placeholder => 'Last name', :class => 'center-it' %><br/><Br />
			  <%= f.text_field :job_title, :placeholder => 'Title', :class => 'center-it' %><br/><br />
			  <%= f.text_field :phone, :placeholder => 'Phone', :class => 'center-it' %><br/><br />
  			  <%= f.text_field :email, :placeholder => 'Email address', :class => 'center-it' %><br/><br />

  			  <%= f.file_field :avatar %>

			<div><%= f.submit 'Create', :class => 'pure-button pure-button-secondary center-it' %></div>
	<% end %>
	</div>

	<div class="right-side-new-person">
		..
	</div>


</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>